<div style="text-align: center;">
<span style="font-family:Courier New; font-size:18px;">
Machine learning approach on gross agricultural production dataset<br>
20/05/2026<br>
Petar Tumbas Fanny Hakim <br><br>
</span>
</div>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<span style="font-family:Courier New; font-size:20px;">
<b>Part 1.</b> <br>
<b>What Data and Why this Data</b>
</span>

blablablabla

<span style="font-family:Courier New; font-size:20px;">
<b>Part 2.</b> <br>
<b>Data import and inspection</b>
</span>

In [6]:
data = pd.read_csv("FAO_PIN_Merged.csv")
data.head(10)

,Country or Area,element_code,Element,Year,Unit,Value,category
0,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2021,Int. $,113.74,Food_PIN
1,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2020,Int. $,118.09,Food_PIN
2,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2019,Int. $,112.55,Food_PIN
3,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2018,Int. $,96.07,Food_PIN
4,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2017,Int. $,100.02,Food_PIN
5,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2016,Int. $,102.34,Food_PIN
6,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2015,Int. $,95.99,Food_PIN
7,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2014,Int. $,101.67,Food_PIN
8,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2013,Int. $,94.29,Food_PIN
9,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2012,Int. $,97.21,Food_PIN

In [ ]:
print(data.shape) #(rows, columns)
print(data.columns)
print(data.dtypes)

(52652, 7)
Index(['Country or Area', 'element_code', 'Element', 'Year', 'Unit', 'Value',
       'category'],
      dtype='object')
Country or Area     object
element_code         int64
Element             object
Year                 int64
Unit                object
Value              float64
category            object
dtype: object

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52652 entries, 0 to 52651
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country or Area  52652 non-null  object
 1   element_code     52652 non-null  int64
 2   Element          52652 non-null  object
 3   Year             52652 non-null  int64
 4   Unit             52652 non-null  object
 5   Value            52652 non-null  float64
 6   category         52652 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 2.8+ MB

In [9]:
data.count()

Country or Area    52652
element_code       52652
Element            52652
Year               52652
Unit               52652
Value              52652
category           52652
dtype: int64

In [ ]:
pd.set_option('display.max_rows', None)
data['Country or Area']

0                                              Afghanistan
1                                              Afghanistan
2                                              Afghanistan
3                                              Afghanistan
4                                              Afghanistan
5                                              Afghanistan
6                                              Afghanistan
7                                              Afghanistan
8                                              Afghanistan
9                                              Afghanistan
10                                             Afghanistan
11                                             Afghanistan
12                                             Afghanistan
13                                             Afghanistan
14                                             Afghanistan
15                                             Afghanistan
16                                             Afghanistan
17                                             Afghanistan
18                                             Afghanistan
19                                             Afghanistan
20                                             Afghanistan
21                                             Afghanistan
22                                             Afghanistan
23                                             Afghanistan
24                                             Afghanistan
25                                             Afghanistan
26                                             Afghanistan
27                                             Afghanistan
28                                             Afghanistan
29                                             Afghanistan
30                                             Afghanistan
31                                             Afghanistan
32                                             Afghanistan
33                                             Afghanistan
34                                             Afghanistan
35                                             Afghanistan
36                                             Afghanistan
37                                             Afghanistan
38                                             Afghanistan
39                                             Afghanistan
40                                             Afghanistan
41                                             Afghanistan
42                                             Afghanistan
43                                             Afghanistan
44                                             Afghanistan
45                                             Afghanistan
46                                             Afghanistan
47                                             Afghanistan
48                                             Afghanistan
49                                             Afghanistan
50                                             Afghanistan
51                                             Afghanistan
52                                             Afghanistan
53                                             Afghanistan
54                                             Afghanistan
55                                             Afghanistan
56                                             Afghanistan
57                                             Afghanistan
58                                             Afghanistan
59                                             Afghanistan
60                                             Afghanistan
61                                             Afghanistan
62                                             Afghanistan
63                                             Afghanistan
64                                             Afghanistan
65                                             Afghanistan
66                                             Afghanistan
67                                             Afghanistan
68                                             Afghanistan
69                                             Afghanistan
70                                             Afghanistan
71                                             Afghanistan
72                                             Afghanistan
73                                             Afghanistan
74                                             Afghanistan
75                                             Afghanistan
76                                             Afghanistan
77                                             Afghanistan
78                                             Afghanistan
79                                             Afghanistan
80                                             Afghanistan
81                                             Afghanistan
82                                             Afghanistan
83                                             Afghanistan
84                                             Afghanistan
85                                             Afghanistan
86                                             Afghanistan
87                                             Afghanistan
88                                             Afghanistan
89                                             Afghanistan
90                                             Afghanistan
91                                             Afghanistan
92                                             Afghanistan
93                                             Afghanistan
94                                             Afghanistan
95                                             Afghanistan
96                                             Afghanistan
97                                             Afghanistan
98                                             Afghanistan
99                                             Afghanistan
100                                            Afghanistan
101                                            Afghanistan
102                                            Afghanistan
103                                            Afghanistan
104                                            Afghanistan
105                                            Afghanistan
106                                            Afghanistan
107                                            Afghanistan
108                                            Afghanistan
109                                            Afghanistan
110                                            Afghanistan
111                                            Afghanistan
112                                            Afghanistan
113                                            Afghanistan
114                                            Afghanistan
115                                            Afghanistan
116                                            Afghanistan
117                                            Afghanistan
118                                            Afghanistan
119                                            Afghanistan
120                                            Afghanistan
121                                            Afghanistan
122                                                 Africa
123                                                 Africa
124                                                 Africa
125                                                 Africa
126                                                 Africa
127                                                 Africa
128                                                 Africa
129                                                 Africa
130                                                 Africa
131                                                 Africa
132                                                 Africa
133                                                 Africa
134                                                 Africa
135                                                 Africa
136                                                 Africa
137                                                 Africa
138                                                 Africa
139                                                 Africa
140                                                 Africa
141                                                 Africa
142                                                 Africa
143                                                 Africa
144                                                 Africa
145                                                 Africa
146                                                 Africa
147                                                 Africa
148                                                 Africa
149                                                 Africa
150                                                 Africa
151                                                 Africa
152                                                 Africa
153                                                 Africa
154                                                 Africa
155                                                 Africa
156                                                 Africa
157                                                 Africa
158                                                 Africa
159                                                 Africa
160                                                 Africa
161                                                 Africa
162                                                 Africa
163                                                 Africa
164                                                 Africa
165                                                 Africa
166                                                 Africa
167                                                 Africa
168                                                 Africa
169                                                 Africa
170                                                 Africa
171                                                 Africa
172                                                 Africa
173                                                 Africa
174                                                 Africa
175                                                 Africa
176                                                 Africa
177                                                 Africa
178                                                 Africa
179                                                 Africa
180                                                 Africa
181                                                 Africa
182                                                 Africa
183                                                 Africa
184                                                 Africa
185                                                 Africa
186                                                 Africa
187                                                 Africa
188                                                 Africa
189                                                 Africa
190                                                 Africa
191                                                 Africa
192                                                 Africa
193                                                 Africa
194                                                 Africa
195                                                 Africa
196                                                 Africa
197                                                 Africa
198                                                 Africa
199                                                 Africa
200                                                 Africa
201                                                 Africa
202                                                 Africa
203                                                 Africa
204                                                 Africa
205                                                 Africa
206                                                 Africa
207                                                 Africa
208                                                 Africa
209                                                 Africa
210                                                 Africa
211                                                 Africa
212                                                 Africa
213                                                 Africa
214                                                 Africa
215                                                 Africa
216                                                 Africa
217                                                 Africa
218                                                 Africa
219                                                 Africa
220                                                 Africa
221                                                 Africa
222                                                 Africa
223                                                 Africa
224                                                 Africa
225                                                 Africa
226                                                 Africa
227                                                 Africa
228                                                 Africa
229                                                 Africa
230                                                 Africa
231                                                 Africa
232                                                 Africa
233                                                 Africa
234                                                 Africa
235                                                 Africa
236                                                 Africa
237                                                 Africa
238                                                 Africa
239                                                 Africa
240                                                 Africa
241                                                 Africa
242                                                 Africa
243                                                 Africa
244                                                Albania
245                                                Albania
246                                                Albania
247                                                Albania
248                                                Albania
249                                                Albania
250                                                Albania
251                                                Albania
252                                                Albania
253                                                Albania
254                                                Albania
255                                                Albania
256                                                Albania
257                                                Albania
258                                                Albania
259                                                Albania
260                                                Albania
261                                                Albania
262                                                Albania
263                                                Albania
264                                                Albania
265                                                Albania
266                                                Albania
267                                                Albania
268                                                Albania
269                                                Albania
270                                                Albania
271                                                Albania
272                                                Albania
273                                                Albania
274                                                Albania
275                                                Albania
276                                                Albania
277                                                Albania
278                                                Albania
279                                                Albania
280                                                Albania
281                                                Albania
282                                                Albania
283                                                Albania
284                                                Albania
285                                                Albania
286                                                Albania
287                                                Albania
288                                                Albania
289                                                Albania
290                                                Albania
291                                                Albania
292                                                Albania
293                                                Albania
294                                                Albania
295                                                Albania
296                                                Albania
297                                                Albania
298                                                Albania
299                                                Albania
300                                                Albania
301                                                Albania
302                                                Albania
303                                                Albania
304                                                Albania
305                                                Albania
306                                                Albania
307                                                Albania
308                                                Albania
309                                                Albania
310                                                Albania
311                                                Albania
312                                                Albania
313                                                Albania
314                                                Albania
315                                                Albania
316                                                Albania
317                                                Albania
318                                                Albania
319                                                Albania
320                                                Albania
321                                                Albania
322                                                Albania
323                                                Albania
324                                                Albania
325                                                Albania
326                                                Albania
327                                                Albania
328                                                Albania
329                                                Albania
330                                                Albania
331                                                Albania
332                                                Albania
333                                                Albania
334                                                Albania
335                                                Albania
336                                                Albania
337                                                Albania

In [ ]:
data['Country or Area'].unique() # we need to separate areas and conuntries

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Americas',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia',
       'Australia', 'Australia and New Zealand', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Caribbean', 'Central African Republic',
       'Central America', 'Central Asia', 'Chad', 'Chile', 'China',
       'China, Hong Kong SAR', 'China, Macao SAR', 'China, mainland',
       'Other non-specified areas', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Eastern Africa', 'Eastern Asia',
       'Eastern Europe', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Europe', 'European Union (27)', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Land Locked Developing Countries',
       "Lao People's Democratic Republic", 'Latvia',
       'Least Developed Countries', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Low Income Food Deficit Countries',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Melanesia', 'Mexico', 'Micronesia',
       'Micronesia (Federated States of)', 'Middle Africa', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Net Food Importing Developing Countries',
       'Netherlands (Kingdom of the)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Macedonia',
       'Northern Africa', 'Northern America', 'Northern Europe', 'Norway',
       'Oceania', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Polynesia', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Small Island Developing States', 'Solomon Islands', 'Somalia',
       'South Africa', 'South America', 'South Sudan',
       'South-eastern Asia', 'Southern Africa', 'Southern Asia',
       'Southern Europe', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Western Africa',
       'Western Asia', 'Western Europe', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [ ]:
data.describe()

       element_code          Year         Value
count  52652.000000  52652.000000  52652.000000
mean     293.000000   1992.111905     92.828808
std      141.001339     17.624093     74.124524
min      152.000000   1961.000000      3.080000
25%      152.000000   1977.000000     63.670000
50%      293.000000   1993.000000     89.820000
75%      434.000000   2007.000000    104.200000
max      434.000000   2021.000000   2056.200000

In [ ]:
data = data.drop(columns=['Element','Unit','category'])

In [20]:
pd.reset_option('display.max_rows')
data #essentially this is the final dataset we will need

      Country or Area  element_code  Year   Value
0         Afghanistan           152  2021  113.74
1         Afghanistan           152  2020  118.09
2         Afghanistan           152  2019  112.55
3         Afghanistan           152  2018   96.07
4         Afghanistan           152  2017  100.02
...               ...           ...   ...     ...
52647        Zimbabwe           434  1965   79.60
52648        Zimbabwe           434  1964   86.02
52649        Zimbabwe           434  1963   77.80
52650        Zimbabwe           434  1962   86.04
52651        Zimbabwe           434  1961   83.56

[52652 rows x 4 columns]