<div style="text-align: center;">
<span style="font-family:Courier New; font-size:18px;">
Machine learning approach on gross agricultural production dataset<br>
20/05/2026<br>
Petar Tumbas Fanny Hakim <br><br>
</span>
</div>

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<span style="font-family:Courier New; font-size:20px;">
<b>Part 1.</b> <br>
<b>What Data and Why this Data</b>
</span>

blablablabla

<span style="font-family:Courier New; font-size:20px;">
<b>Part 2.</b> <br>
<b>Data import and inspection</b>
<br>
<b>Production [tons], Yield [kg/ha], Area [ha]</b>
</span>

In [32]:
data = pd.read_csv("Production_Crops_Livestock_E_All_Data.csv")
data.head(10)
# data.tail(10)
data2 = pd.read_csv("FAO_PIN_Merged.csv")

/tmp/ipykernel_28878/3673865152.py:1: DtypeWarning: Columns (11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143,146,149,152,155,158,161,164,167,170,173,176,179,182,185,188,191,194,197,200) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Production_Crops_Livestock_E_All_Data.csv")

In [33]:
print(data.shape) #(rows, columns)
print(data.columns)
print(data.dtypes)

(78974, 201)
Index(['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item Code (CPC)',
       'Item', 'Element Code', 'Element', 'Unit', 'Y1961',
       ...
       'Y2021N', 'Y2022', 'Y2022F', 'Y2022N', 'Y2023', 'Y2023F', 'Y2023N',
       'Y2024', 'Y2024F', 'Y2024N'],
      dtype='object', length=201)
Area Code            int64
Area Code (M49)     object
Area                object
Item Code            int64
Item Code (CPC)     object
                    ...
Y2023F              object
Y2023N              object
Y2024              float64
Y2024F              object
Y2024N              object
Length: 201, dtype: object

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78974 entries, 0 to 78973
Columns: 201 entries, Area Code to Y2024N
dtypes: float64(64), int64(3), object(134)
memory usage: 121.1+ MB

In [35]:
data.count()

Area Code          78974
Area Code (M49)    78974
Area               78974
Item Code          78974
Item Code (CPC)    78974
                   ...
Y2023F             71752
Y2023N              1321
Y2024              65755
Y2024F             66461
Y2024N               544
Length: 201, dtype: int64

In [36]:
# pd.set_option('display.max_rows', None)
data['Area']

0                                             Afghanistan
1                                             Afghanistan
2                                             Afghanistan
3                                             Afghanistan
4                                             Afghanistan
                               ...
78969    Net Food Importing Developing Countries (NFIDCs)
78970    Net Food Importing Developing Countries (NFIDCs)
78971    Net Food Importing Developing Countries (NFIDCs)
78972    Net Food Importing Developing Countries (NFIDCs)
78973    Net Food Importing Developing Countries (NFIDCs)
Name: Area, Length: 78974, dtype: object

In [37]:
data['Area'].unique() # we need to separate areas and conuntries

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belgium-Luxembourg', 'Belize',
       'Benin', 'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'China, Hong Kong SAR', 'China, Macao SAR', 'China, mainland',
       'China, Taiwan Province of', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', 'Czechoslovakia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guadeloupe', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia (Federated States of)',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands (Kingdom of the)',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Réunion', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Serbia and Montenegro', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Sudan (former)', 'Suriname', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Türkiye',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'USSR', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Yugoslav SFR', 'Zambia', 'Zimbabwe', 'World', 'Africa',
       'Eastern Africa', 'Middle Africa', 'Northern Africa',
       'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries (LDCs)',
       'Land Locked Developing Countries (LLDCs)',
       'Small Island Developing States (SIDS)',
       'Low Income Food Deficit Countries (LIFDCs)',
       'Net Food Importing Developing Countries (NFIDCs)'], dtype=object)

In [38]:
data.describe()

,Area Code,Item Code,Element Code,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,...,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2022,Y2023,Y2024
count,78974.000000,78974.000000,78974.000000,5.731800e+04,5.732500e+04,5.732400e+04,5.733900e+04,5.733400e+04,5.739500e+04,5.739900e+04,...,7.106500e+04,7.117000e+04,7.140500e+04,7.078400e+04,7.086100e+04,7.100200e+04,7.107200e+04,7.124100e+04,7.103500e+04,6.575500e+04
mean,1324.567541,867.966331,5409.061843,1.514904e+06,1.548964e+06,1.583002e+06,1.630083e+06,1.664009e+06,1.704872e+06,1.749381e+06,...,3.181752e+06,3.228411e+06,3.268816e+06,3.326681e+06,3.347043e+06,3.382336e+06,3.466879e+06,3.503911e+06,3.580686e+06,3.803037e+06
std,2202.488084,1467.460908,101.349759,1.587450e+07,1.615756e+07,1.645865e+07,1.695414e+07,1.731770e+07,1.776352e+07,1.817828e+07,...,3.610064e+07,3.659429e+07,3.689543e+07,3.733722e+07,3.723158e+07,3.760673e+07,3.877931e+07,3.931957e+07,4.038929e+07,4.181009e+07
min,1.000000,15.000000,5111.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,89.000000,358.000000,5312.000000,7.030000e+02,7.310000e+02,7.520500e+02,7.773300e+02,7.993250e+02,8.000000e+02,8.174500e+02,...,1.332400e+03,1.345000e+03,1.341260e+03,1.231375e+03,1.232000e+03,1.239425e+03,1.229730e+03,1.235900e+03,1.225150e+03,1.200000e+03
50%,170.000000,587.000000,5412.000000,6.450800e+03,6.576600e+03,6.727200e+03,6.978400e+03,7.018500e+03,7.256400e+03,7.500000e+03,...,1.090400e+04,1.094480e+04,1.094660e+04,1.085755e+04,1.088380e+04,1.087505e+04,1.092365e+04,1.093394e+04,1.094481e+04,1.051870e+04
75%,272.000000,1037.000000,5510.000000,6.432743e+04,6.668771e+04,6.900000e+04,7.101340e+04,7.269325e+04,7.501200e+04,7.770000e+04,...,1.194800e+05,1.206606e+05,1.212070e+05,1.223685e+05,1.238710e+05,1.241462e+05,1.251600e+05,1.260430e+05,1.260350e+05,1.227580e+05
max,5817.000000,17530.000000,5513.000000,1.342210e+09,1.360092e+09,1.368767e+09,1.381032e+09,1.397533e+09,1.408673e+09,1.428836e+09,...,2.835200e+09,2.935987e+09,2.940738e+09,2.899639e+09,2.966105e+09,3.026009e+09,3.075147e+09,3.054491e+09,3.126272e+09,3.133223e+09

In [39]:
data['Item'].unique()

array(['Almonds, in shell',
       'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw',
       'Apples', 'Apricots', 'Asses', 'Barley', 'Beans, dry',
       'Butter and ghee of sheep milk', 'Butter of cow milk',
       'Buttermilk, dry', 'Camels', 'Cantaloupes and other melons',
       'Cattle', 'Cattle fat, unrendered',
       'Cheese from milk of goats, fresh or processed',
       'Cheese from milk of sheep, fresh or processed', 'Chickens',
       'Cotton lint, ginned', 'Cotton seed', 'Cottonseed oil',
       'Edible offal of cattle, fresh, chilled or frozen',
       'Edible offal of goat, fresh, chilled or frozen',
       'Edible offal of sheep, fresh, chilled or frozen',
       'Edible offals of camels and other camelids, fresh, chilled or frozen',
       'Fat of camels', 'Figs', 'Game meat, fresh, chilled or frozen',
       'Goat fat, unrendered', 'Goats', 'Grapes',
       'Hen eggs in shell, fresh', 'Horses', 'Linseed', 'Maize (corn)',
       'Meat of camels, fresh or chilled',
       'Meat of cattle with the bone, fresh or chilled',
       'Meat of chickens, fresh or chilled',
       'Meat of goat, fresh or chilled',
       'Meat of sheep, fresh or chilled', 'Millet', 'Molasses',
       'Mules and hinnies', 'Mustard seed', 'Natural honey',
       'Oil of linseed', 'Oil of sesame seed', 'Olive oil', 'Olives',
       'Onions and shallots, dry (excluding dehydrated)', 'Oranges',
       'Other berries and fruits of the genus vaccinium n.e.c.',
       'Other citrus fruit, n.e.c.', 'Other fruits, n.e.c.',
       'Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.',
       'Other pulses n.e.c.',
       'Other stimulant, spice and aromatic crops, n.e.c.',
       'Other stone fruits', 'Other vegetables, fresh n.e.c.',
       'Peaches and nectarines', 'Pears', 'Peas, dry',
       'Pistachios, in shell', 'Plums and sloes', 'Potatoes',
       'Raw cane or beet sugar (centrifugal only)',
       'Raw hides and skins of cattle',
       'Raw hides and skins of goats or kids',
       'Raw hides and skins of sheep or lambs', 'Raw milk of camel',
       'Raw milk of cattle', 'Raw milk of goats', 'Raw milk of sheep',
       'Raw silk (not thrown)', 'Rice', 'Seed cotton, unginned',
       'Sesame seed', 'Sheep', 'Sheep fat, unrendered',
       'Shorn wool, greasy, including fleece-washed shorn wool',
       'Silk-worm cocoons suitable for reeling', 'Skim milk of cows',
       'Soya beans', 'Sugar beet', 'Sugar cane', 'Sunflower seed',
       'Sunflower-seed oil, crude', 'Walnuts, in shell', 'Watermelons',
       'Wheat', 'Beef and Buffalo Meat, primary', 'Butter and Ghee',
       'Cattle and Buffaloes', 'Cereals, primary', 'Cheese (All Kinds)',
       'Citrus Fruit, Total', 'Eggs Primary',
       'Fibre Crops, Fibre Equivalent', 'Fruit Primary', 'Meat, Poultry',
       'Meat, Total', 'Milk, Total', 'Oilcrops, Cake Equivalent',
       'Oilcrops, Oil Equivalent', 'Poultry Birds', 'Pulses, Total',
       'Roots and Tubers, Total', 'Sheep and Goat Meat',
       'Sheep and Goats', 'Skim Milk & Buttermilk, Dry',
       'Sugar Crops Primary', 'Treenuts, Total', 'Vegetables Primary',
       'Beer of barley, malted', 'Bees',
       'Broad beans and horse beans, dry',
       'Broad beans and horse beans, green', 'Buffalo',
       'Buffalo fat, unrendered', 'Cabbages', 'Carrots and turnips',
       'Cauliflowers and broccoli', 'Cheese from whole cow milk',
       'Cherries', 'Chestnuts, in shell',
       'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)',
       'Cucumbers and gherkins', 'Dates', 'Ducks',
       'Edible offal of buffalo, fresh, chilled or frozen',
       'Edible offal of pigs, fresh, chilled or frozen',
       'Edible offals of horses and other equines, fresh, chilled or frozen',
       'Eggplants (aubergines)',
       'Eggs from other birds in shell, fresh, n.e.c.', 'Fat of pigs',
       'Geese', 'Green garlic',
       'Green tea (not fermented), black tea (fermented) and partly fermented tea, in immediate packings of a content not exceeding 3 kg',
       'Groundnut oil', 'Hop cones', 'Horse meat, fresh or chilled',
       'Leeks and other alliaceous vegetables', 'Lemons and limes',
       'Lettuce and chicory', 'Margarine and shortening',
       'Meat of asses, fresh or chilled',
       'Meat of buffalo, fresh or chilled',
       'Meat of pig with the bone, fresh or chilled',
       'Meat of turkeys, fresh or chilled', 'Mushrooms and truffles',
       'Oats', 'Okra', 'Onions and shallots, green', 'Other beans, green',
       'Other meat of mammals, fresh or chilled', 'Peas, green',
       'Pumpkins, squash and gourds', 'Quinces',
       'Raw hides and skins of buffaloes', 'Raw milk of buffalo', 'Rye',
       'Sorghum', 'Sour cherries', 'Soya bean oil', 'Spinach',
       'Strawberries', 'Swine / pigs',
       'Tangerines, mandarins, clementines', 'Tomatoes', 'Turkeys',
       'Unmanufactured tobacco', 'Vetches', 'Wine', 'Artichokes',
       'Bananas', 'Cheese from skimmed cow milk', 'Chick peas, dry',
       'Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw',
       'Groundnuts, excluding shelled', 'Lentils, dry',
       'Locust beans (carobs)',
       'Meat of rabbits and hares, fresh or chilled',
       'Other tropical fruits, n.e.c.', 'Pomelos and grapefruits',
       'Rabbits and hares', 'Rape or colza seed',
       'Rapeseed or canola oil, crude', 'Safflower-seed oil, crude',
       'Triticale', 'Avocados', 'Beeswax', 'Cashew nuts, in shell',
       'Cassava, fresh', 'Castor oil seeds', 'Cocoa beans',
       'Coffee, green',
       'Kenaf, and other textile bast fibres, raw or retted',
       'Mangoes, guavas and mangosteens', 'Oil of palm kernel',
       'Oil palm fruit', 'Palm kernels', 'Palm oil', 'Pig fat, rendered',
       'Pineapples', 'Sisal, raw', 'Sweet potatoes', 'Green corn (maize)',
       'Taro', 'Yams', 'Asparagus', 'Canary seed', 'Cereals n.e.c.',
       'Cream, fresh', 'Flax, raw or retted', 'Ghee from cow milk',
       'Lupins', 'Maté leaves', 'Meat of ducks, fresh or chilled',
       'Meat of geese, fresh or chilled',
       'Meat of mules, fresh or chilled', 'Oil of maize',
       'Other fibre crops, raw, n.e.c.', 'Other oil seeds, n.e.c.',
       'Papayas', 'Peppermint, spearmint', 'Safflower seed',
       'Skim milk and whey powder', 'String beans', 'Tallow',
       'Tea leaves', 'Tung nuts', 'Whey, dry', 'Whole milk powder',
       'Whole milk, condensed', 'Whole milk, evaporated',
       'Evaporated & Condensed Milk', 'Hazelnuts, in shell',
       'Blueberries', 'Coconut oil', 'Cow peas, dry', 'Currants',
       'Ginger, raw', 'Hempseed', 'Kiwi fruit', 'Persimmons',
       'Raspberries', 'Skim milk, condensed', 'True hemp, raw or retted',
       'Buckwheat', 'Cheese from milk of buffalo, fresh or processed',
       'Gooseberries', 'Mixed grain', 'Other pome fruits', 'Poppy seed',
       'Whey, condensed', 'Yoghurt', 'Cranberries', 'Coconuts, in shell',
       'Pigeon peas, dry', 'Plantains and cooking bananas', 'Areca nuts',
       'Butter of buffalo milk', 'Coir, raw', 'Ghee from buffalo milk',
       'Jute, raw or retted', 'Natural rubber in primary forms',
       'Other sugar crops n.e.c.', 'Chicory roots',
       'Edible roots and tubers with high starch or inulin content, n.e.c., fresh',
       'Yautia', 'Bambara beans, dry', 'Fonio', 'Karite nuts (sheanuts)',
       'Kola nuts', 'Pepper (Piper spp.), raw',
       'Nutmeg, mace, cardamoms, raw', 'Quinoa', 'Brazil nuts, in shell',
       'Meat of other domestic camelids, fresh or chilled',
       'Meat of other domestic rodents, fresh or chilled',
       'Other camelids', 'Other rodents', 'Pyrethrum, dried flowers',
       'Balata, gutta-percha, guayule, chicle and similar natural gums in primary forms or in plates, sheets or strip',
       'Cashewapple', 'Ramie, raw or retted',
       'Meat of pigeons and other birds n.e.c., fresh, chilled or frozen',
       'Melonseed', 'Skim milk, evaporated',
       'Cinnamon and cinnamon-tree flowers, raw',
       'Cloves (whole stems), raw', 'Other birds', 'Tallowtree seeds',
       'Vanilla, raw', 'Agave fibres, raw, n.e.c.', 'Cassava leaves',
       'Abaca, manila hemp, raw',
       'Snails, fresh, chilled, frozen, dried, salted or in brine, except sea snails',
       'Kapok fibre, raw', 'Kapok fruit', 'Kapokseed in shell',
       'Jojoba seeds'], dtype=object)

In [40]:
# Food_data = data[data['category'] == 'Food_PIN']
# Agri_data = data[data['category'] == 'Agri_PIN'].reset_index(drop=True)

In [41]:
# Food_data.info()
# Agri_data.info()

In [42]:
# Food_data.tail(10)

In [43]:
# Agri_data.tail(10)

In [44]:
# Food_data = Food_data.drop(columns=['Element','Unit','category'])
# Agri_data = Agri_data.drop(columns=['Element','Unit','category'])

In [45]:
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')
# Food_data #essentially this is the final dataset we will need

In [46]:
Areas = [
    'Africa',
    'Americas',
    'Asia',
    'Australia and New Zealand',
    'Central America',
    'Central Asia',
    'China, mainland',
    'Other non-specified areas',
    'Eastern Africa',
    'Eastern Asia',
    'Eastern Europe',
    'Europe',
    'European Union (27)',
    'Land Locked Developing Countries',
    'Least Developed Countries',
    'Low Income Food Deficit Countries',
    'Micronesia (Federated States of)',
    'Middle Africa',
    'Net Food Importing Developing Countries',
    'Northern Africa',
    'Northern America',
    'Northern Europe',
    'Oceania',
    'Polynesia',
    'Small Island Developing States',
    'South America',
    'South-eastern Asia',
    'Southern Africa',
    'Southern Asia',
    'Southern Europe',
    'Western Africa',
    'Western Asia',
    'Western Europe',
    'World'
]

In [47]:
coffee = data[data["Item"] == "Coffee, green"].reset_index(drop=True)

In [48]:
coffee.head(10)

,Area Code,Area Code (M49),Area,Item Code,Item Code (CPC),Item,Element Code,Element,Unit,Y1961,...,Y2021N,Y2022,Y2022F,Y2022N,Y2023,Y2023F,Y2023N,Y2024,Y2024F,Y2024N
0,7,'024,Angola,656,'01610,"Coffee, green",5312,Area harvested,ha,350000.0,...,NaN,15432.00,I,NaN,18290.00,I,NaN,22060.00,I,NaN
1,7,'024,Angola,656,'01610,"Coffee, green",5412,Yield,kg/ha,481.7,...,NaN,337.30,E,NaN,340.60,E,NaN,343.80,E,NaN
2,7,'024,Angola,656,'01610,"Coffee, green",5510,Production,t,168600.0,...,NaN,5206.00,A,NaN,6229.00,A,NaN,7584.00,A,NaN
3,23,'084,Belize,656,'01610,"Coffee, green",5312,Area harvested,ha,NaN,...,NaN,74.00,I,NaN,75.00,I,NaN,76.00,I,NaN
4,23,'084,Belize,656,'01610,"Coffee, green",5412,Yield,kg/ha,NaN,...,NaN,1217.90,E,NaN,1201.80,E,NaN,1180.60,E,NaN
5,23,'084,Belize,656,'01610,"Coffee, green",5510,Production,t,NaN,...,NaN,89.53,E,NaN,89.56,E,NaN,89.57,E,NaN
6,53,'204,Benin,656,'01610,"Coffee, green",5312,Area harvested,ha,5000.0,...,NaN,284.00,E,NaN,283.00,E,NaN,284.00,E,NaN
7,53,'204,Benin,656,'01610,"Coffee, green",5412,Yield,kg/ha,418.0,...,NaN,194.50,E,NaN,194.50,E,NaN,194.50,E,NaN
8,53,'204,Benin,656,'01610,"Coffee, green",5510,Production,t,2090.0,...,NaN,55.30,E,NaN,55.09,E,NaN,55.13,E,NaN
9,19,'068,Bolivia (Plurinational State of),656,'01610,"Coffee, green",5312,Area harvested,ha,6000.0,...,NaN,25954.00,A,NaN,25496.00,A,NaN,25119.00,A,NaN

In [49]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Columns: 201 entries, Area Code to Y2024N
dtypes: float64(64), int64(3), object(134)
memory usage: 515.2+ KB

In [50]:
coffee["Area"].unique()

array(['Angola', 'Belize', 'Benin', 'Bolivia (Plurinational State of)',
       'Brazil', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Central African Republic', 'China', 'China, mainland',
       'China, Taiwan Province of', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Cuba',
       'Democratic Republic of the Congo', 'Dominica',
       'Dominican Republic', 'Ecuador', 'El Salvador',
       'Equatorial Guinea', 'Ethiopia', 'Ethiopia PDR', 'Fiji',
       'French Polynesia', 'Gabon', 'Ghana', 'Guadeloupe', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Honduras', 'India', 'Indonesia',
       'Jamaica', 'Kenya', "Lao People's Democratic Republic", 'Liberia',
       'Madagascar', 'Malawi', 'Malaysia', 'Martinique', 'Mauritius',
       'Mexico', 'Mozambique', 'Myanmar', 'Nepal', 'New Caledonia',
       'Nicaragua', 'Nigeria', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Puerto Rico', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Sierra Leone', 'Spain',
       'Sri Lanka', 'Suriname', 'Thailand', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Uganda',
       'United Republic of Tanzania', 'United States of America',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Yemen', 'Zambia', 'Zimbabwe', 'World', 'Africa', 'Eastern Africa',
       'Middle Africa', 'Western Africa', 'Americas', 'Northern America',
       'Central America', 'Caribbean', 'South America', 'Asia',
       'Eastern Asia', 'Southern Asia', 'South-eastern Asia',
       'Western Asia', 'Europe', 'Southern Europe', 'Oceania',
       'Melanesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries (LDCs)',
       'Land Locked Developing Countries (LLDCs)',
       'Small Island Developing States (SIDS)',
       'Low Income Food Deficit Countries (LIFDCs)',
       'Net Food Importing Developing Countries (NFIDCs)'], dtype=object)

In [51]:
# coffee.to_csv("coffee.csv", index=False)

In [52]:
# data2["Country or Area"] = data2["Country or Area"].str.strip()
data2 = data2[~data2["Country or Area"].isin(Areas)]

In [53]:
Countries = list(data2["Country or Area"].unique()) # countries and columns filtered from the main data set
data = data[data["Area"].isin(Countries)]
data = data.drop(columns=['Area Code (M49)', 'Item Code (CPC)', 'Element Code', 'Unit'])

years = list(range(1961, 2025))

for year in years:
    str_year = str(year)
    data = data.drop(columns="Y"+str_year+"F")
    data = data.drop(columns="Y"+str_year+"N")

In [54]:
data.head(10)

,Area Code,Area,Item Code,Item,Element,Y1961,Y1962,Y1963,Y1964,Y1965,...,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2022,Y2023,Y2024
0,2,Afghanistan,221,"Almonds, in shell",Area harvested,0.0,0.0,0.0,0.0,0.0,...,14676.0,19481.00,19793.00,20053.00,29203.00,22134.0,36862.00,36462.00,37000.00,39794.00
1,2,Afghanistan,221,"Almonds, in shell",Yield,NaN,NaN,NaN,NaN,NaN,...,1652.1,1685.90,1378.80,1716.10,1308.30,1775.9,1743.20,1742.00,1810.80,1741.90
2,2,Afghanistan,221,"Almonds, in shell",Production,0.0,0.0,0.0,0.0,0.0,...,24246.0,32843.00,27291.00,34413.00,38205.00,39307.0,64256.00,63515.00,67000.00,69315.64
3,2,Afghanistan,711,"Anise, badian, coriander, cumin, caraway, fenn...",Area harvested,NaN,NaN,NaN,NaN,NaN,...,25000.0,24500.00,26160.00,25220.00,25293.00,25558.0,25357.00,25403.00,25439.00,25400.00
4,2,Afghanistan,711,"Anise, badian, coriander, cumin, caraway, fenn...",Yield,NaN,NaN,NaN,NaN,NaN,...,720.0,707.50,697.00,708.00,704.10,703.0,705.00,704.00,704.00,704.30
5,2,Afghanistan,711,"Anise, badian, coriander, cumin, caraway, fenn...",Production,NaN,NaN,NaN,NaN,NaN,...,18000.0,17333.33,18234.12,17855.82,17807.76,17965.9,17876.49,17883.38,17908.59,17889.49
6,2,Afghanistan,515,Apples,Area harvested,2220.0,2220.0,2220.0,2350.0,2480.0,...,13038.0,19365.00,26847.00,28381.00,27559.00,25643.0,30463.00,30163.00,31000.00,32280.00
7,2,Afghanistan,515,Apples,Yield,6801.8,6801.8,6801.8,7829.8,8225.8,...,6882.4,7276.20,6348.70,7652.70,9083.20,10562.6,10559.40,10556.00,10451.60,10341.80
8,2,Afghanistan,515,Apples,Production,15100.0,15100.0,15100.0,18400.0,20400.0,...,89733.0,140903.00,170443.00,217192.00,250324.00,270857.0,321672.00,318402.00,324000.00,333837.85
9,2,Afghanistan,526,Apricots,Area harvested,4820.0,4820.0,4820.0,5100.0,5370.0,...,9116.0,8595.00,18067.00,18510.00,17719.00,17481.0,27082.00,26731.00,25374.00,23132.00

In [55]:
data.to_csv("DATA.csv", index=False)